### ISSUE TITLE
average energy and full spectrum calculation

### ISSUE THREAD

**Issue by IvanDudinets** [EliousMondal/1D-TDSE_solver#1]
Hello, Mr. Md Elious Ali Mondal

Thank you very much for your python implementation of TDSE solver. I have a question about this solver.
Can it calculate  the average energy <psi(t)| H(t) |psi(t)> and the probabilities |<psi(t)| psi_n>|^2 vs time, where 
H(t) is the Hamiltonian, psi(t) is the solution to TDSE and psi_n is an instantaneous eigenstate of H(t)? 

Thank you.

**Comment by EliousMondal** [comment]
Hi, I did not implement the calculation of any expectation values. But since at every time step we get the wavefunction in position basis, we can integrate in the position basis to get can any expectation value.  It does stores the |cn(t)|^2 value at every time step through the Coeff2 function in the coefficients.py file

**Comment by IvanDudinets** [comment]
Thanks for the answer. Could you please comment on full spectrum of the Hamiltonian? Is it simple to implement using your repository?

**Comment by EliousMondal** [comment]
You can use the TISE_solver.py to get the eigenspectrum at any instant of time. Line26 in this file is a = np.linspace(min(V(x,t)),1,20). This line specifies the window in which you want to look for eigenvalues. Increasing the range and incorporating more fine spacing for shooting method will give you more eigenvalues. For example, trying np.linspace(min(V(x,t)),10,200) will look for all eigenvalues in the range [min(V(x,t),10] atomic units. Here 200 is to make the search better, using 500 makes the search even better.
